### ISSUE TITLE
Window not showing/Which model is correct?

### ISSUE THREAD

**Issue by CycleMark** [nickoala/edgetpu-on-pi#1]
Hi,

This looks cool. Though weirdly I can't see the view window open up. All I get is:

pi@kobukiMxnet:~/edgetpu/python-tflite-source/edgetpu $ python3 demo/detect_capture_crop.py --model test_data/detect.tflite --label test_data/imagenet_labels.txt
/usr/local/lib/python3.6/site-packages/picamera/encoders.py:521: PiCameraAlphaStripping: using alpha-stripping to convert to non-alpha format; you may find the equivalent alpha format faster
  "using alpha-stripping to convert to non-alpha "
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/lib/python3.6/site-packages/picamera/mmalobj.py", line 1227, in wrapper
    self._pool.send_buffer(block=False)
  File "/usr/local/lib/python3.6/site-packages/picamera/mmalobj.py", line 1931, in send_buffer
    super(MMALPortPool, self).send_buffer(port, block, timeout)
  File "/usr/local/lib/python3.6/site-packages/picamera/mmalobj.py", line 1881, in send_buffer
    raise PiCameraMMALError(mmal.MMAL_EAGAIN, 'no buffers available')
picamera.exc.PiCameraMMALError: no buffers available: Resource temporarily unavailable; try again later
Traceback (most recent call last):

Any idea why the view window won't open?

Also am I using the correct model. I downloaded from 

https://www.tensorflow.org/lite/models/object_detection/overview#starter_model

Thanks

Mark

**Comment by nickoala** [comment]
It seems having trouble reading data from the camera. Is another program using the camera? Use `raspistill` to make sure the camera is working.

**Comment by CycleMark** [comment]
Yeah the camera is fine, and no nothing else it using it. I assumed those messages were the ones you'd mentioned you were getting?

**Comment by nickoala** [comment]
Oops, sorry. Yes, that's the error showing up for me too. But my preview window shows up fine on my 5-inch HDMI LCD display. Are you using VNC to view the desktop? The preview shows on HDMI only.

**Comment by CycleMark** [comment]
Yep I am using VNC - Though after some digging I found out the reason (as you mentioned) why is wasn't working. But also a way to get it to work under VNC Options->TroubleShooting->"Enable Direct Capture" (Or something like that) and it works.

What data set are you using?

I've just started using this one:

https://github.com/PINTO0309/TPU-MobilenetSSD

`python3 demo/detect_capture_crop.py --model test_data/mobilenet_ssd_v2_coco_quant_postprocess.tflite --label test_data/coco_labels.txt
`

But's its v slow 2fps. Not overly sure it's using the TPU as the light isn't "breathing". Any idea?


Thanks

Mark
